#!/usr/bin/env escript
%% -*- erlang -*-
%%! -smp enable -mnesia debug verbose dir 'Mnesia.nonode@nohost'
-include_lib("records.hrl").
main(_) ->
       file:read_link_info("records.hrl"),
	arfolyam:start(),
        %% mnesia:delete_table(daily_values),
        %% mnesia:create_table(daily_values, 
        %%                      [{disc_copies,[node()]},
        %%                       {type, ordered_set},
        %%                       {attributes, 
        %%                        record_info(fields, daily_value)},
        %%                       {record_name, daily_value}]),
        arfolyam:read_portfolio(),
	arfolyam:calculate_portfolio(),
	mnesia:dump_to_textfile("mnesia.txt").
