#!/usr/bin/env escript
%% -*- erlang -*-
%%! -smp enable -mnesia debug verbose dir 'Mnesia.nonode@nohost'
-include_lib("records.hrl").
main(_) ->
        shell_default:cd("/Users/evabihari/Erlang_apps/vienna_life_value"),
        file:read_link_info("records.hrl"),
        try
        %%     mnesia:restore("backup.bup",[{default_op, recreate_tables}])
               mnesia:load_textfile("mnesia.txt")
        catch
            {aborted,enoent} -> 
                io:format("Backup does not exist, starting with clean database",[]);
            {error,open} -> io:format("File does not exist, starting with clean database",[])
        end,
	arfolyam:start(),
        arfolyam:read_portfolio(),
	arfolyam:calculate_portfolio(),
        mnesia:dump_to_textfile("mnesia.txt"),
        mnesia:backup("backup.bup").
